### ISSUE TITLE
Merge master back to develop because I approved Harrison's PR

### ISSUE THREAD

**Issue by NinchuKyo** [NinchuKyo/nobadsharrisonrepo#8]
Should have made PR for develop and then PR from develop to master.

get-rekt-huge-change should have been merged with develop, and then PR created for develop.

TODO - resolve merge conflicts when merging master back to develop
I blame Harrison, so you look at this.

**Comment by HarrisonMulder** [comment]
How bout this - 2 step process since I don't like Git much and the web conflict resolve tool really sucks and I can't wrap my head around it :p 

1.  Push change to develop DELETING EVERYTHINGGGGG MWAHAHAHAHAHAH
2.  Merge master into develop w/ no conflicts :)

**Comment by NinchuKyo** [comment]
1. Okay I DELETE ALL OF develop
2. I leave develop-harrison because I like the name
3. Rip auto generated code
4. Git add-on in VS
5. LOLOOOLOOLOLOL

**Comment by NinchuKyo** [comment]
Also 6. I leave this ticket open because I like the name

**Comment by HarrisonMulder** [comment]
I close lel
